### ISSUE TITLE
Use of the Loupe within the DTRichTextEditor causes a crash

### ISSUE THREAD

**Issue by slm-2015** [Cocoanetics/DTRichTextEditor#1]
Hi,

I am using the rich text editor (DTRichTextEditor) in our project and are experiencing an issue with the use of the magnifying glass loupe (i.e. cursor positioning function) that is causing our app to crash.

Here are the repro steps:
- Embed the rich text editor into a skeleton app that contains a view that holds the DTRichTextEditor component. You can find our example project that [does this here.](http://sendfile.pl/pobierz/400838---Xi7o.html)
- Start the app. Do not type any letters, just press and hold for a few seconds to bring out the loupe for cursor positioning.
- Lift your finger press to make the loupe disappear
- Press and hold again for a few seconds to bring out the loupe again.
- _Bug:_ This makes the project crash at: [DTLoupeView refreshLoupeContent] / [DTLoupeLayerDelegate displayLayer:]

The problem can appear on other occasions, but the steps above are the most reliable to reproduce the issue.  We are testing on iOS 8.  xcode 6.3 with iOS sdk 8.3

I'd would like to offer $200 USD to the person who can produce a fix for this issue.  If the fix requires a reimplementation the magnification using the modern snapshotting methods, I'd understand that this would need more work and would pay $800 USD instead of $200 USD.  Transfer of payment on a successful code review from Oliver and subject to final testing within my project.

Many thanks,
Simon.

**Comment by odrobnik** [comment]
Here is a copy of the issue on the DTLoupe project which is where the bug would need to be fixed: https://github.com/Cocoanetics/DTLoupe/issues/1

**Comment by Jon889** [comment]
I haven't worked out why yet, but the the crash doesn't occur if the text selection drag handles are added to the DTTextSelectionView itself rather than it's superviews (DTTextSelectonView.m: 391, 407)

**Comment by odrobnik** [comment]
@Jon889 maybe you could send a pull request with your change so that @slm-2015 can test it?

**Comment by odrobnik** [comment]
Fixed in https://github.com/Cocoanetics/DTLoupe/releases/tag/1.5.6
