### ISSUE TITLE
How do we build the demo project?

### ISSUE THREAD

**Issue by cerupcat** [Cocoanetics/DTRichTextEditor#6]
The demo project doesn't seem to build.

```
#import <DTCoreText/DTCoreText.h> not found
```

**Comment by odrobnik** [comment]
The header search path includes `$(SYMROOT)/../..` so that if you have the DTCoreText submodule present the headers can be found. Please make sure that you cloned the project recursively or loading all linked submodules before attempting to build it.

**Comment by odrobnik** [comment]
PS: I just tried it out, again. And the Demo App builds without problem.
