### ISSUE TITLE
Couldn't display after inserting an image

### ISSUE THREAD

**Issue by ChiHoc** [Cocoanetics/DTRichTextEditor#7]
Here is a bug.

NSAttachmentAttributeName is the variable of system. 

Rewriting DTAttachmentAttributeName leads to the issue that couldn't display after inserting an image with iPhone devices.

**Comment by adib** [comment]
In the demo app when run on the iPhone Simulator (iOS 9), inserting an image from the photo library has no effect. After having selected the image and dismissing the image picker, the supposedly inserted image is nowhere to be found in the text.
