### ISSUE TITLE
unable to compile on Xcode 7

### ISSUE THREAD

**Issue by rdmeyers** [Cocoanetics/DTRichTextEditor#8]
As usual, new Xcode, new issues!  Anyway, the following line in DTRichTextEditorView.m is preventing compilation:

```
#pragma mark Text Input Delegate and Text Input Tokenizer
@synthesize inputDelegate;
```

The error it is producing is:

```
The current deployment target does not support automated __weak references
```

I have attempted this on both an existing project which use to compile fine, and on a completely new project.  I have all targets set to iOS 8.0.  I have also tried 6.0 and 7.1.

Do you have any thoughts?

**Comment by odrobnik** [comment]
Some part in here is having a too old deployment target.

**Comment by rdmeyers** [comment]
It appears that the "iOS Deployment Target" setting under the "(null) - Deployment" category of a couple of the Static Library Build Settings was not getting updated.  Forcing a value there made everything happy :-)

**Comment by odrobnik** [comment]
@rdmeyers if you could document the specific static library targets which you needed to change we can see that we fix the project. Or - better yet - you could provide a pull request with the changes.

**Comment by rdmeyers** [comment]
DTRichTextEditor is set to iOS 4.3.
DTWebArchive is set to iOS 5.0.
DTLoupe is set to iOS 5.0.

These worked just fine under Xcode 6.4, but 7.0 complains as noted above.

**Comment by odrobnik** [comment]
There should be macros from `DTWeakSupport.h` in place to prevent using of weak when building for 4.3...

**Comment by rdmeyers** [comment]
I am not sure there are many devices out in the field running iOS 4.3 ;-)  Xcode 7 won't even target less than 6.0 now!

Anyway, having gotten past the previous error on the Synthesize line, now the same variable within the private declaration is raising a new error. Thus this line:

```
__unsafe_unretained id<UITextInputDelegate> inputDelegate;
```

Is raising this error:

```
Existing instance variable 'inputDelegate' for __weak property 'inputDelegate' must be __weak
```

**Comment by odrobnik** [comment]
I see that inputDelegate is defined as weak in iOS 9 SDK. This makes it impossible to support iOS 4.3 any more as deployment target if you are building with iOS 9 SDK.

I believe the correct fix is to set the deployment target for "Static Library" to be iOS 5.0 or higher.

**Comment by rdmeyers** [comment]
OK, I am able to compile RTE 1.6.9 which seems to be the last build under the old setup from when I purchased it.  So now I am attempting to migrate to RTE 1.6.11 to keep current, however it has significant changes in the #imports paths in the various headers.  For example:

```
// RTE 1.6.9
#import "DTLoupeView.h"
#import "DTCoreText.h"
#import "DTCoreGraphicsUtils.h"
```

is now:

```
// RTE 1.6.11
#import <DTLoupe/DTLoupeView.h>
#import <DTCoreText/DTCoreText.h>
#import <DTFoundation/DTCoreGraphicsUtils.h>
```

How do I set the project up to find these now?  I previous set things up per your YouTube demo.  If I simply change the import statements to using the 1.6.9 style, then I get all sorts of "redefinition" errors, so that will not work.  If I leave them as they are, then I get a bunch of "cannot find" errors.  Help!  :-)

**Comment by odrobnik** [comment]
Please use cocoapods, that sets all paths up for you.

Best regards
Oliver Drobnik

@Cocoanetics on Twitter and App.net
www.cocoanetics.com

**Comment by rdmeyers** [comment]
Well you forced me to learn something new (CocoaPods) and I am a better man (and developer) for it.  Everything compiles perfectly.  Thanks!

**Comment by odrobnik** [comment]
@rdmeyers you're welcome! Cocoapods is awesome.

**Comment by Jeswang** [comment]
I am having the same problem, already using cocoapod 0.39.0 with Xcode Version 7.0.1 (7A1001)

```
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'project' do
    platform :ios, '7.1'
    pod 'DTCoreText', :head
        pod 'DTRichTextEditor'
end
```

**Comment by odrobnik** [comment]
@Jeswang make a new issue and add more infos please
