### ISSUE TITLE
Crash on iOS 9

### ISSUE THREAD

**Issue by rdmeyers** [Cocoanetics/DTRichTextEditor#9]
Long-press for selection is crashing the control with the following message:

```
Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'sublayer with non-finite position [inf inf]'
```

The crash appears to be coming from:

```
file: DTLoupeView.m
method: refreshViewContent
line: [_targetRootView.layer renderInContext:ctx];
```

Double tap for selection is not a problem, so the above loupe scenario seems logical.

This same build works fine on iOS 8.x devices.

**Comment by odrobnik** [comment]
@amro Did your changes fix this?

**Comment by Wielkibrat** [comment]
IOS9 seems to have stronger restrictions on rendering the tree. Instead of just hiding the layers with incorrect position/frame you need to remove them from the tree before rendering.
So in 

```
- (void)refreshLoupeContent
```

replace hiding bad layers with:

```
NSMutableArray *brokenLayers = [[NSMutableArray alloc]init];
[self gatherInvalidLayersInView:_targetRootView brokenLays:brokenLayers];
for(NSObject *obj in brokenLayers){
        if([obj isKindOfClass:[CALayer class]]){
            //probably this part is not needed at all..
            CALayer *layer = (CALayer*)obj;
            layer.frame=CGRectZero;
            layer.hidden=YES;
        }
        else{
            UIView *view = (UIView*)obj;
            [view removeFromSuperview];
        }
    } 
// the loupe is not part of the rendered tree, so we don't need to hide it
[_targetRootView.layer renderInContext:ctx];        
```

gatherInvalidLayersInView

```
- (void)gatherInvalidLayersInView:(UIView *)rootView brokenLays:(NSMutableArray*)brokenLays
{
    NSMutableArray *brokenLayers = [[NSMutableArray alloc]init];
    if ([self layerHasInvalidFrame:rootView.layer] )
    {
        [brokenLayers addObject:rootView.layer];
        [brokenLayers addObject:rootView];
    }

    for (UIView *view in rootView.subviews)
    {
        if ([self layerHasInvalidFrame:view.layer])
        {
            [brokenLayers addObject:view.layer];
            [brokenLayers addObject:view];
        }

        for (CALayer *layer in view.layer.sublayers)
        {
            if ([self layerHasInvalidFrame:layer])
            {
                [brokenLayers addObject:layer];
            }
        }
        [brokenLays addObjectsFromArray:brokenLayers];
        [self gatherInvalidLayersInView:view brokenLays:brokenLays];
    }   
}
```

**Comment by amro** [comment]
Yes, this is what I found as well. I left a note in the similar issue for DTLoupe.

**Comment by odrobnik** [comment]
Discussion should be continued here: https://github.com/Cocoanetics/DTLoupe/issues/7  - is it an option to set the broken layers to CGRectZero instead of removing them to avoid a crash elsewhere?

**Comment by Daij-Djan** [comment]
@amro @Cocoanetics 
Explained and Fixed in 'Use of the DTLoupe within the DTRichTextEditor causes a crash under IOS9'

the fix I found is: http://stackoverflow.com/questions/32919051/sublayer-with-non-finite-position-inf-inf

Simply replace CGRectNull with CGRectZero ... I could hardly believe it but that works

DTTextSelectionView.m

```
#pragma mark Utilities
- (CGRect)beginCaretRect
{
    __block CGRect rect = CGRectZero;

    // find the first selection rectangle the has the beginning
    [_selectionRectangles enumerateObjectsUsingBlock:^(DTTextSelectionRect *oneTextSelectionRect, NSUInteger idx, BOOL *stop) {
        if (oneTextSelectionRect.containsStart)
        {
            rect = oneTextSelectionRect.rect;
            rect.size.width = 3.0;
            *stop = YES;
        }
    }];

    return rect;
}

- (CGRect)endCaretRect
{
    __block CGRect rect = CGRectZero;

    // find the first selection rectangle from the back the has the end
    [_selectionRectangles enumerateObjectsWithOptions:NSEnumerationReverse usingBlock:^(DTTextSelectionRect *oneTextSelectionRect, NSUInteger idx, BOOL *stop) {
        if (oneTextSelectionRect.containsEnd)
        {
            rect = oneTextSelectionRect.rect;
            rect.origin.x += rect.size.width;
            rect.size.width = 3.0;
            *stop = YES;
        }
    }];

    return rect;
}
```

**Comment by amro** [comment]
That (sadly) makes sense.

Edit: I have a PR up to work around this in DTLoupe, but I think a fix here is important too.

**Comment by amro** [comment]
(I suggest the workaround in DTLoupe as well because someone using DTLoupe without DTRTE could run into the same issue.)

**Comment by Daij-Djan** [comment]
@amro no the DTLoupe fix alone isn't enough but it can't hurt :)

**Comment by Daij-Djan** [comment]
@amro your fix doesn't catch this. I even swizzled renderInContext and it doesn't work either. :/
and I can't believe this works (sad.)

**Comment by amro** [comment]
You tried the PR, right? If that didn't prevent the crash then we shouldn't merge the PR

Thanks,
Amro

**Comment by odrobnik** [comment]
I merged the PR, @rdmeyers please check it out

**Comment by rdmeyers** [comment]
The fix is good!  No more crash on devices and simulators.
